### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by DeadlyDad** [martymcguire/inkscape-openscad-poly#13]
First off, I really appreciate all of the work that you have put into this.  If you could do a little more, it would be greatly appreciated.  I see that the output has smoothness hardcoded and the relevant(?) line says `subdivide_cubic_path(sp, 0.2)  # TODO: smoothness preference`.  Can you please add that (and anything else helpful) to the interface?

**Comment by martymcguire** [comment]
Hi @DeadlyDad ! Thanks for this report as well!

As I mentioned in #12 I'm not actively maintaining this extension at this time but I'd be happy to accept a pull request that adds this particular preference interface bit.
