### ISSUE TITLE
Other units than px, % or none (such as mm) should be handled

### ISSUE THREAD

**Issue by bzamecnik** [martymcguire/inkscape-openscad-poly#4]
Same SVG as in #3.

```
Traceback (most recent call last):
  File "openscad-poly.py", line 45, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "openscad-poly.py", line 39, in effect
    parser.parse()
  File "/Users/bzamecnik/.config/inkscape/extensions/openscad_poly/svg_parser.py", line 229, in parse
    self.svgWidth = self.getLength('width', 354) * 0.28222
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by martymcguire** [comment]
This is an issue that crops up when using this (aging) plugin with recent versions of Inkscape when a document has no units. Try setting the units to px or mm in document settings.

**Comment by bzamecnik** [comment]
When I set from mm to px, it finally produced a nice SCAD file! When I looked at the source the `getLength()` supports only 'px', '%' or '' (no units). Nice thing is that I can just modify the python script and it has an immediate effect, no need for building anything. :)

Thanks for help, Marty!

Maybe I could try to fix some other bugs:
- the SCAD file contains some invalid lines at the beginning:
```
('UNITS:', 1541.312, 'px')
('UNITS:', 1203.1851, 'px')
```
- when there's a more complex shape, multiple modules are created, instead of a single group
- it should handle other units (such as mm) without a crash

I like more this approach of directly exporting to SCAD rather than to intermediate DXF. Then there's no need to import anything, just include an SCAD file.

**Comment by martymcguire** [comment]
Hmm. Not sure where the spurious lines in the OpenSCAD are coming from. Maybe some bad handling of (new?) metadata in the Inkscape SVG file?

Unfortunately, I haven't had time to play with this code in a long time. Any improvements are most welcome!!

**Comment by baxerus** [comment]
See my pull request #5.
And please test it. I only tested it myself so far...
