### ISSUE TITLE
Out-dated installation folder for Mac OS in README.md

### ISSUE THREAD

**Issue by glaza** [martymcguire/inkscape-openscad-poly#7]
Hi Marty,

First of all, thank you for this plug-in, it is fantastic!

Just wanted to let you know that Inkscape installs differently on High Sierra and Mojave.
[Official Instructions here](https://inkscape.org/release/inkscape-0.92.4/mac-os-x/macports/dl/)

The folder we should copy the ```src/*``` is: ```/opt/local/share/inkscape/extensions```

Thanks,

George

**Comment by martymcguire** [comment]
Thanks! I've updated the README.
