### ISSUE TITLE
Changes for Inkscape 1.0?

### ISSUE THREAD

**Issue by martymcguire** [martymcguire/inkscape-openscad-poly#9]
Got an email about possible updates to make:

> Thank you for providing this extension for Inkscape users!
> 
> This is just to let you know that most 3rd party Inkscape extensions,
like the one you made, probably will not work with the upcoming new
Inkscape version, the long-awaited version 1.0.
> 
> Here is the info you need to update this extension, so that it will work
with 1.0 and future versions.
> https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0
> 
> If you have further questions, you can contact Inkscape developers via
mailing lists (https://lists.inkscape.org/postorius/lists/?all-lists),
forum (https://inkscape.org/forums/extensions/), or the chatroom
(https://chat.inkscape.org/channel/team_devel)
> 
> If you have already updated it, please disregard this message.

**Comment by chenjinya** [comment]
I found it can works in inkscape 1.0
